# -- Alignment -- #
pm_alignment_administration_homepage:
    path:     /administration/alignement
    defaults: { _controller: PMCharacterBundle:Alignment:index }

pm_alignment_administration_insert:
    path:     /administration/alignement/insertion
    defaults: { _controller: PMCharacterBundle:Alignment:register }

pm_alignment_administration_list:
    path:     /administration/alignement/liste
    defaults: { _controller: PMCharacterBundle:Alignment:list }
    
pm_alignment_administration_view:
    path:     /administration/alignement/vue/{slug}
    defaults: { _controller: PMCharacterBundle:Alignment:view }
    requirements:
        slug:  \S{0,255}
    
pm_alignment_administration_edit:
    path:     /administration/alignement/editer/{slug}
    defaults: { _controller: PMCharacterBundle:Alignment:edit }
    requirements:
        slug:  \S{0,255}
    
pm_alignment_administration_delete:
    path:     /administration/alignement/supprimer/{slug}
    defaults: { _controller: PMCharacterBundle:Alignment:delete }
    requirements:
        slug:  \S{0,255}

# -- ClassDnD -- #
pm_classdnd_administration_homepage:
    path:     /administration/classe
    defaults: { _controller: PMCharacterBundle:ClassDnD:index }

pm_classdnd_administration_insert:
    path:     /administration/classe/insertion
    defaults: { _controller: PMCharacterBundle:ClassDnD:register }

pm_classdnd_administration_list:
    path:     /administration/classe/liste
    defaults: { _controller: PMCharacterBundle:ClassDnD:list }
    
pm_classdnd_administration_view:
    path:     /administration/classe/vue/{slug}
    defaults: { _controller: PMCharacterBundle:ClassDnD:view }
    requirements:
        slug:  \S{0,255}
    
pm_classdnd_administration_edit_bab:
    path:     /administration/classe/editer/bab/{slug}
    defaults: { _controller: PMCharacterBundle:ClassDnD:editBAB }
    requirements:
        slug:  \S{0,255}
    
pm_classdnd_administration_edit_st:
    path:     /administration/classe/editer/st/{slug}
    defaults: { _controller: PMCharacterBundle:ClassDnD:editST }
    requirements:
        slug:  \S{0,255}
    
pm_classdnd_administration_edit:
    path:     /administration/classe/editer/{slug}
    defaults: { _controller: PMCharacterBundle:ClassDnD:edit }
    requirements:
        slug:  \S{0,255}
    
pm_classdnd_administration_delete:
    path:     /administration/classe/supprimer/{slug}
    defaults: { _controller: PMCharacterBundle:ClassDnD:delete }
    requirements:
        slug:  \S{0,255}

# -- Race -- #
pm_race_administration_homepage:
    path:     /administration/race
    defaults: { _controller: PMCharacterBundle:Race:index }

pm_race_administration_insert:
    path:     /administration/race/insertion
    defaults: { _controller: PMCharacterBundle:Race:register }

pm_race_administration_list:
    path:     /administration/race/liste
    defaults: { _controller: PMCharacterBundle:Race:list }
    
pm_race_administration_view:
    path:     /administration/race/vue/{slug}
    defaults: { _controller: PMCharacterBundle:Race:view }
    requirements:
        slug:  \S{0,255}
    
pm_race_administration_edit:
    path:     /administration/race/editer/{slug}
    defaults: { _controller: PMCharacterBundle:Race:edit }
    requirements:
        slug:  \S{0,255}
    
pm_race_administration_delete:
    path:     /administration/race/supprimer/{slug}
    defaults: { _controller: PMCharacterBundle:Race:delete }
    requirements:
        slug:  \S{0,255}

# -- Language -- #
pm_language_administration_homepage:
    path:     /administration/langue
    defaults: { _controller: PMCharacterBundle:Language:index }

pm_language_administration_insert:
    path:     /administration/langue/insertion
    defaults: { _controller: PMCharacterBundle:Language:register }

pm_language_administration_list:
    path:     /administration/langue/liste
    defaults: { _controller: PMCharacterBundle:Language:list }
    
pm_language_administration_view:
    path:     /administration/langue/vue/{slug}
    defaults: { _controller: PMCharacterBundle:Language:view }
    requirements:
        slug:  \S{0,255}
    
pm_language_administration_edit:
    path:     /administration/langue/editer/{slug}
    defaults: { _controller: PMCharacterBundle:Language:edit }
    requirements:
        slug:  \S{0,255}
    
pm_language_administration_delete:
    path:     /administration/langue/supprimer/{slug}
    defaults: { _controller: PMCharacterBundle:Language:delete }
    requirements:
        slug:  \S{0,255}

# -- CharacterUsed -- #
pm_characterused_administration_homepage:
    path:     /administration/personnage
    defaults: { _controller: PMCharacterBundle:CharacterUsed:index }

pm_characterused_administration_insert:
    path:     /administration/personnage/insertion
    defaults: { _controller: PMCharacterBundle:CharacterUsed:register }

pm_characterused_administration_insert_abilities:
    path:     /administration/personnage/insertion/caracteristiques/{slug}
    defaults: { _controller: PMCharacterBundle:CharacterUsed:registerAbilities }
    requirements:
        slug:  \S{0,255}

pm_characterused_administration_insert_skills:
    path:     /administration/personnage/insertion/competences/{slug}
    defaults: { _controller: PMCharacterBundle:CharacterUsed:registerSkills }
    requirements:
        slug:  \S{0,255}

pm_characterused_administration_list:
    path:     /administration/personnage/liste
    defaults: { _controller: PMCharacterBundle:CharacterUsed:list }
    
pm_characterused_administration_view:
    path:     /administration/personnage/vue/{slug}
    defaults: { _controller: PMCharacterBundle:CharacterUsed:view }
    requirements:
        slug:  \S{0,255}
    
pm_characterused_administration_edit:
    path:     /administration/personnage/editer/{slug}
    defaults: { _controller: PMCharacterBundle:CharacterUsed:edit }
    requirements:
        slug:  \S{0,255}
    
pm_characterused_administration_delete:
    path:     /administration/personnage/supprimer/{slug}
    defaults: { _controller: PMCharacterBundle:CharacterUsed:delete }
    requirements:
        slug:  \S{0,255}

# -- Skill -- #
pm_skill_administration_homepage:
    path:     /administration/competence
    defaults: { _controller: PMCharacterBundle:Skill:index }

pm_skill_administration_insert:
    path:     /administration/competence/insertion
    defaults: { _controller: PMCharacterBundle:Skill:register }

pm_skill_administration_list:
    path:     /administration/competence/liste
    defaults: { _controller: PMCharacterBundle:Skill:list }
    
pm_skill_administration_view:
    path:     /administration/competence/vue/{slug}
    defaults: { _controller: PMCharacterBundle:Skill:view }
    requirements:
        slug:  \S{0,255}
    
pm_skill_administration_edit:
    path:     /administration/competence/editer/{slug}
    defaults: { _controller: PMCharacterBundle:Skill:edit }
    requirements:
        slug:  \S{0,255}
    
pm_skill_administration_delete:
    path:     /administration/competence/supprimer/{slug}
    defaults: { _controller: PMCharacterBundle:Skill:delete }
    requirements:
        slug:  \S{0,255}

# -- Size -- #
pm_size_administration_homepage:
    path:     /administration/taille
    defaults: { _controller: PMCharacterBundle:Size:index }

pm_size_administration_insert:
    path:     /administration/taille/insertion
    defaults: { _controller: PMCharacterBundle:Size:register }

pm_size_administration_list:
    path:     /administration/taille/liste
    defaults: { _controller: PMCharacterBundle:Size:list }
    
pm_size_administration_view:
    path:     /administration/taille/vue/{slug}
    defaults: { _controller: PMCharacterBundle:Size:view }
    requirements:
        slug:  \S{0,255}
    
pm_size_administration_edit:
    path:     /administration/taille/editer/{slug}
    defaults: { _controller: PMCharacterBundle:Size:edit }
    requirements:
        slug:  \S{0,255}
    
pm_size_administration_delete:
    path:     /administration/taille/supprimer/{slug}
    defaults: { _controller: PMCharacterBundle:Size:delete }
    requirements:
        slug:  \S{0,255}

# -- Level -- #
pm_level_administration_homepage:
    path:     /administration/niveau
    defaults: { _controller: PMCharacterBundle:Level:index }

pm_level_administration_insert:
    path:     /administration/niveau/insertion
    defaults: { _controller: PMCharacterBundle:Level:register }

pm_level_administration_list:
    path:     /administration/niveau/liste
    defaults: { _controller: PMCharacterBundle:Level:list }
    
pm_level_administration_view:
    path:     /administration/niveau/vue/{level}
    defaults: { _controller: PMCharacterBundle:Level:view }
    requirements:
        level:  \S{0,255}
    
pm_level_administration_edit:
    path:     /administration/niveau/editer/{level}
    defaults: { _controller: PMCharacterBundle:Level:edit }
    requirements:
        level:  \S{0,255}
    
pm_level_administration_delete:
    path:     /administration/niveau/supprimer/{level}
    defaults: { _controller: PMCharacterBundle:Level:delete }
    requirements:
        level:  \S{0,255}
        
# -- Ability -- #
pm_ability_administration_homepage:
    path:     /administration/caractéristique
    defaults: { _controller: PMCharacterBundle:Ability:index }

pm_ability_administration_insert:
    path:     /administration/caractéristique/insertion
    defaults: { _controller: PMCharacterBundle:Ability:register }

pm_ability_administration_list:
    path:     /administration/caractéristique/liste
    defaults: { _controller: PMCharacterBundle:Ability:list }
    
pm_ability_administration_view:
    path:     /administration/caractéristique/vue/{slug}
    defaults: { _controller: PMCharacterBundle:Ability:view }
    requirements:
        slug:  \S{0,255}
    
pm_ability_administration_edit:
    path:     /administration/caractéristique/editer/{slug}
    defaults: { _controller: PMCharacterBundle:Ability:edit }
    requirements:
        slug:  \S{0,255}
    
pm_ability_administration_delete:
    path:     /administration/caractéristique/supprimer/{slug}
    defaults: { _controller: PMCharacterBundle:Ability:delete }
    requirements:
        slug:  \S{0,255}