services:
    pm_character.characteruseddnd:
        class: PM\CharacterBundle\Service\characterUsedDnD
        arguments: [ "@doctrine.orm.entity_manager", "@security.context", "@pm_character.characterusedability"]
        
    pm_character.characterusedability:
        class: PM\CharacterBundle\Service\characterUsedAbility
        arguments: [ "@doctrine.orm.entity_manager", "@security.context"]
        
    pm_character.characterusedst:
        class: PM\CharacterBundle\Service\characterUsedST
        arguments: [ "@doctrine.orm.entity_manager", "@security.context", "@pm_character.characterusedability"]
        
    pm_character.characterusedaction:
        class: PM\CharacterBundle\Service\characterUsedAction
        arguments: [ "@doctrine.orm.entity_manager", "@security.context"]
        
    pm_character.deletealignment:
        class: PM\CharacterBundle\Service\deleteAlignment
        arguments: [ "@doctrine.orm.entity_manager", "@security.context"]
        
    pm_character.deleteclassdnd:
        class: PM\CharacterBundle\Service\deleteClassDnD
        arguments: [ "@doctrine.orm.entity_manager", "@security.context"]
        
    pm_character.deletelanguage:
        class: PM\CharacterBundle\Service\deleteLanguage
        arguments: [ "@doctrine.orm.entity_manager", "@security.context"]
        
    pm_character.deleterace:
        class: PM\CharacterBundle\Service\deleteRace
        arguments: [ "@doctrine.orm.entity_manager", "@security.context"]
        
    pm_character.deleteskill:
        class: PM\CharacterBundle\Service\deleteSkill
        arguments: [ "@doctrine.orm.entity_manager", "@security.context"]
        
    pm_character.deletesize:
        class: PM\CharacterBundle\Service\deleteSize
        arguments: [ "@doctrine.orm.entity_manager", "@security.context"]
