<?php

namespace PM\CharacterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CharacterUsedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterUsedRepository extends EntityRepository
{
}
