pm_weapon:
    resource: "@PMWeaponBundle/Resources/config/routing.yml"
    prefix:   /

pm_monster:
    resource: "@PMMonsterBundle/Resources/config/routing.yml"
    prefix:   /

pm_welcome:
    resource: "@PMWelcomeBundle/Resources/config/routing.yml"
    prefix:   /

pm_character:
    resource: "@PMCharacterBundle/Resources/config/routing.yml"
    prefix:   /

pm_game:
    resource: "@PMGameBundle/Resources/config/routing.yml"
    prefix:   /

pm_user:
    resource: "@PMUserBundle/Resources/config/routing.yml"
    prefix:   /administration/utilisateurs

app:
    resource: @AppBundle/Controller/
    type:     annotation

# -- FOS UserBundle -- #
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /utilisateur/profile
    
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /administration/utilisateur/nouveau
    
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /utilisateur/resetting
    
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /utilisateur/profile
    
# -- JS Routing -- #    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"