# -- Routes des utilisateurs -- #
# Pattern extend : /utilisateurs #
pm_user_administration_homepage:
    pattern:  /
    defaults: { _controller: PMUserBundle:User:index }

pm_user_administration_list:
    pattern:  /liste
    defaults: { _controller: PMUserBundle:User:UsersList }
    
pm_user_administration_view:
    pattern:  /{user_id}
    defaults: { _controller: PMUserBundle:User:View}
    requirements:
        user_id:  \d+
    
pm_user_administration_edit:
    pattern:  /{user_id}/edition
    defaults: { _controller: PMUserBundle:User:edit}
    requirements:
        user_id:  \d+
        
pm_user_ajax_password:
    pattern:  /1234-password
    defaults: { _controller: PMUserBundle:Registration:AjaxPassword }
    requirements:
        _method: POST
    options:
        expose: true
        