# -- Routes des utilisateurs -- #
pm_user_homepage:
    pattern:  /
    defaults: { _controller: PMUserBundle:User:index }

pm_user_list:
    pattern:  /liste
    defaults: { _controller: PMUserBundle:User:UsersList }
    
pm_user_view:
    pattern:  /user/{id_utilisateur}
    defaults: { _controller: PMUserBundle:User:View}
    requirements:
        id_utilisateur:  \d+