<?php

namespace PM\WeaponBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WeaponTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeaponTypeRepository extends EntityRepository
{
}
