<?php

namespace PM\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameRaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRaceRepository extends EntityRepository
{
}
