<?php

namespace PM\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameClassRepository extends EntityRepository
{
}
