<?php

namespace PM\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameCharacterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameCharacterRepository extends EntityRepository
{
}
