<?php

namespace PM\WelcomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DiceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiceTypeRepository extends EntityRepository
{
}
