<?php

namespace PM\WelcomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DiceFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiceFormRepository extends EntityRepository
{
}
