services:
    pm_weapon.weapontypeaction:
        class: PM\MonsterBundle\Service\weaponTypeAction
        arguments: [ "@doctrine.orm.entity_manager", "@security.context"]
        
    pm_weapon.weaponaction:
        class: PM\MonsterBundle\Service\weaponAction
        arguments: [ "@doctrine.orm.entity_manager", "@security.context"]