<?php

namespace PM\MonsterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpeedSpecialInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeedSpecialInstanceRepository extends EntityRepository
{
}
